### ISSUE TITLE
Stats for specific pages

### ISSUE THREAD

**Issue by flxmts** [BVPyro/front#103]
Is there a way to establish stats via umami dor the several pages ob bvpk.org, for instance https://bvpk.org/umweltbelastung-feuerwerk or bvpk.org/petition although its going to forward to an external page?

**Comment by linozen** [comment]
https://umami.bvpk.org/website/1/bpvk.org?view=url Isn't that what your are looking for?

**Comment by flxmts** [comment]
pretty much YES... ;)

just one more question: why isn't /petition listed, yet? do we need to add it manually or can we trigger to have it there? would be to interesting to see how many people reach the page vs. how many sign the petition... thx

**Comment by linozen** [comment]
I didn't include the tracking script on `/petition`. It's included since this morning. Sorry!
