### ISSUE TITLE
Style issues in bvpk.org/aktuelles/positionspapier-silvester

### ISSUE THREAD

**Issue by flxmts** [BVPyro/front#104]
When creating https://bvpk.org/aktuelles/positionspapier-silvester I stretched the possibilities of our cms via manual editing of the source code. It looks okay, but there still ist some minor layout issues. maybe there's some quick fixes for this.

- line spacing in table of contents is way to wide
- bullte points of the last four paragraphs in "Zusammenfassung" need to be indented
- Content of 1st column of the table in chapter __2. Aktuelle Gesetzeslage__ needs to be indented

**Comment by linozen** [comment]
I fixed the most obvious issues in the CMS.
