### ISSUE TITLE
feat: create bvpk.org/itz and link from footer

### ISSUE THREAD

**Issue by flxmts** [BVPyro/front#112]
we'd like to support "initiative transparente zivilgesellschaft" and provide the necessary info on our web page.

pls
- create bvpk.org/itz
- alternatively, bvpk.org/transparenz/itz might be used, as we'll take online more pages regarding that topic
- link to cms

- create link to bvpk.org/itz in footer
- the link should consist of the logo of ITZ (https://www.transparency.de/typo3conf/ext/lf_base/Resources/Frontend/build/assets/images/logo_initiative-transparente-zivilgesellschaft.svg)
- but can only be used once the page with the info has been approved by transparencs international
- i'd therefore suggest to embed an alternative, simple file (e.g. a monocoloured image file) to create the link
- the icon could appear in a new line between the social media buttons and "© 2022 BVPK e.V. Alle Rechte vorbehalten." or at the level of the social media media buttons, aligned to the right / left limit of the page (with a lot of space to the social media buttons)

**Comment by linozen** [comment]
This is done :tada:
