### ISSUE TITLE
Spiegeln einer externen Seite

### ISSUE THREAD

**Issue by flxmts** [BVPyro/front#121]
Im Kontext der neuen Homepage soll auch eine Übersicht der relavanten Rechtsvorschriften rund um Feuerwerk erscheinen. Da eine solche Übersicht von niemandem so kontinuierlich gepflegt wird von der Gewerbeaufsicht BaWü haben, haben wir dort angefragt, ob die die Vorschruftensammlung übernehmen können, Zendenz positiv.

https://gewerbeaufsicht.baden-wuerttemberg.de/sprengstoffrecht-vorschriften

Gibt es eine Möglichkeit, den Inhalt der Seite aus BaWü auf unserer und in unserem Style zu "spiegeln", sodass Änderungen auf der Seite aus BaWü automatisch übernommen werden?

**Comment by linozen** [comment]
possible :)
