### ISSUE TITLE
OVERVIEW: PRIORISATION OF ISSUES

### ISSUE THREAD

**Issue by flxmts** [BVPyro/front#46]
Ich fand es eher umständlich die Issues über Projects zu priorisieren, deswegen hier eine Liste dazu. Issues bitte in dieser Reihenfolge bearbeiten.

- [x] bug: fix dead link in footer to insta bug
- [x] bug: format and content automated mails bug
- [x] feat: implementation fundraising box
- [x] bug: Finish CSV-SPG
- [x] feat: Changes in Membership Form enhancement
- [ ] feat: press releases page enhancement
- [ ] feat: Newsfeed revamp on homepage enhancement
- [ ] feat: Allow editing of SEO header tags via CMS enhancement

**Comment by linozen** [comment]
I'll close this now and would argue that we use priority labels (high - medium - low) in the future.
