### ISSUE TITLE
feat: Add auto-filling BIC field

### ISSUE THREAD

**Issue by linozen** [BVPyro/front#63]
# Feature Request

**Describe the Feature Request**

A BIC field should be added in which is auto-filled upon entering a valid IBAN number.

**Describe Preferred Solution**

Something that uses https://openiban.com/ or a self-hosted version thereof

**Describe Alternatives**

Staying with the current IBAN-only validation.

**Comment by flxmts** [comment]
The current version seems to work properly without auto-filled BIC field.
