### ISSUE TITLE
create bvpk.org/petition

### ISSUE THREAD

**Issue by flxmts** [BVPyro/front#89]
wir werden in kürze eine breit angelegte petition starten, die wir auf einem der gängigen petitionspprtale schalten werden. Die sache wird sehr breit beworben werden, es wird auch print-material mit link geben. deswegen hätte ich gerne einen permanenten link mit einer URL von uns, von der wir automatisiert weiterleiten - für den fall, dass due petition offline genommen wird oder sich die URL auf der plattform ändert.

könntest du bitte die url bvpk.org/ petition anlegen. die seite muss keine inhalte haben, es geht nur darum, von dort weiterzuleiten. die url, auf die weitergeleitet werden soll, teile ich dir asap mit. link ist jetztt schon richtig, um qr-code etc. für die grafikerin zu generieren...

wenn du andere ideen hast, das zu handeln sind diese sehr willkommen.

**Comment by flxmts** [comment]
edit: mir fällt grade ein, dass man auch p.bvpk.org nehmen könnte - weil kürzer. spricht was gegen eine subdomain?

**Comment by flxmts** [comment]
as the link has reached its way to the public and the petition itself isn't online yes, we need to create a quick interim solution. could you please

- [ ] create a simple page for bvpk.org/petition
- [ ] link it to the cms

i'll fill in the content...

**Comment by linozen** [comment]
This is done now and the content - as usual - can be edited [here](https://cms.bvpk.org/admin/content/petition_page).

**Comment by flxmts** [comment]
- [ ] Create forward from bvpk.org/petition to https://www.change.org/p/schutz-und-f%C3%B6rderung-der-feuerwerkskultur
- [ ] Create item "Petition" in main menu, link to https://www.change.org/p/schutz-und-f%C3%B6rderung-der-feuerwerkskultur. A new tab should open upon click on the item
