### ISSUE TITLE
feat: Improve existing Forms

### ISSUE THREAD

**Issue by flxmts** [BVPyro/front#91]
- [x] 2.0 Änderung an allen Formularen
- [x] 2.1 Änderungen an allen Formularen, in denen die Sektion "Versicherung" vorkommt
- [x] 2.2 Änderung an allen Formularen, in denen die Sektion "Fördermitgliedschaft" vorkommt
- [x] 2.3 Änderung in allen Formularen, in denen die Sektion "Förderbeitrag" vorkommt (https://bvpk.org/foerder)

- [x] **2.0 Änderung an allen Formularen**

- [x] Uns erreichen immer wieder Emails, dass Mitgliedsformulare nicht funktionierten. Nach etwas Rumprobiere scheint der Grund folgender zu sein: Wenn in einem (Pflicht)feld ungültige Angaben gemacht werden, werden diese rot markiert. **Nicht markiert werden jedoch gänzlich leere Pflichtfelder.** Genauer: Sie werden makiert, wenn eine Eingabe gemacht, aber wieder gelöscht wurden. Das bringt nicht so viel, wenn sie gänzlich übersehen. Das scheint insbesonder bei dem Feld "Anrede" immer wieder zu passieren. Wir brauchen eine Markierung der unausgefüllten Textfelder. Ich weiß nicht, wie sich einstellen lässt, wann diese erscheint. Eine Option wäre das bekannte Schema "Klicken auf _Senden_-Button immer möglich --> wenn leere Pflichtfelder --> Seite scrollt nach oben und fehlende Felder sind markiert.

- [x] Überprüfen der eingegebenen Daten: Typo "Verfikation" zu "Verifikation" korrigieren oder "zur Verfikation" ersetzen durch "zum Überprüfen" (leichte Sprache für unsere Mitglieder ;))

- [x] Alle Formulare, bei denen dies noch nicht der Fall ist (z.B. https://bvpk.org/grund-foerder) brauchen eine Anbindung ans CMS, sodass selbstständig Text und Bild über den Formularen eingefügt werden können.

- [x] **2.1 Änderungen an allen Formularen, in denen die Sektion "Versicherung" vorkommt**

- [x] Sektion "Versicherung": Textänderung
Der Text, der erscheint, wenn die Checkbox gecheckt wird, wird geändert auf: _Für die Versicherung wird ein zusätzlicher Beitrag von 40,00€/Jahr fällig. Weitere Infos gibt’s [hier](https://media.bvpk.org/versicherung/bvpk_versicherung.pdf). Die Versicherung des BVPK kann ausschließlich zu den im hier verlinkten Dokument genannten Modalitäten in Anspruch genommen werden._

- [x] Sektion Checkboxes, Ende des Formulars
Wenn die Checkbox Versicherung gecheckt wurde, erscheint am Ende des Formulars ein weitere Checkbox mit folgendem Text: _Ich habe die [Informationen und Modalitäten der Feuerwerkversicherung](https://media.bvpk.org/versicherung/bvpk_versicherung.pdf) zur Kenntnis genommen und erkenne diese an._ Erst wenn die Checkbox gecheckt wurde oder die Checkbox bei Sektion "Versicherung" geunchecked wurde, kann das Formular abgeschickt werden.

- [x] **2.2 Änderung an allen Formularen, in denen die Sektion "Fördermitgliedschaft" vorkommt**

Textänderung:

Der Jahresbeitrag für die Grundmitgliedschaft im BVPK beträgt nur 24€/Jahr, um möglichst allen Feuerwerksbegeisterten die Mitgliedschaft im BVPK zu ermöglichen. Für seine Arbeit zum Erhalt des Feuerwerk ist der Verein ständig auf weitere Mittel angewiesen. Mit einer Fördermitgliedschaft unterstützt Du den Verein und die gesamte Community beim Engagement für das Feuerwerk!

Bei einer Fördermitgliedschaft entfällt der Grundbeitrag von 24€/Jahr. Die Fördermitgliedschaft kann jederzeit gekündigt werden.

- [x] **2.3 Änderung in allen Formularen, in denen die Sektion "Förderbeitrag" vorkommt (https://bvpk.org/foerder)**

Textänderung:

~~Der jährliche Förderbeitrag ist der gesamte Förderbeitrag pro Jahr. Der Zahlungsrhythmus bestimmt, in welchem Rhythmus entsprechende Teilbeträge abgebucht werden (z.B. 100€ Jahresbeitrag / quartalsweise = 4 Abbuchungen à 25€ pro Jahr + 24€ Grundbeitrag pro Jahr = 124€ insgesamt pro Jahr). Die Fördermitgliedschaft kann jederzeit gekündigt werden.~~

Mit einer Fördermitgliedschaft unterstützt Du den Verein und die gesamte Community bei seiner Arbeit für das Feuerwerk.

- [ ] **2.4 Änderungen am bisherigen Formular https://bvpk.org/mitglied-werden-firma**

Neue Sektion Upload Erlaubnisschein

→ Wir sollten besprechen wie viel Aufwand das bedeutet sowie wohin und wie die Dateien ggf. übertragen werden.

• Sektionstext: Bitte laden Sie hier eine Kopie Ihrer Erlaubnis nach §7 SprengG hoch. Mögliche Dateiformate: JPG und PDF, max. XX MB.
• Feld zur Auswahl der Datei + Button Upload
• Checkbox: Ich habe keine Erlaubnis nach §7 SprengG
◦ Wenn gecheckt…
▪ ...muss keine Datei hochgeladen werden
▪ ...geht ein Textfeld auf mit Beschreibung: Bitte geben Sie kurz an, warum keine Erlaubnis vorliegt.

**DONE**

~~**2.1 Änderungen am bisherigen Formular https://bvpk.org/mitglied-werden**~~

~~Neu: Angaben überprüfen
Soweit möglich: Nach Ausfüllen des Formulars wird zunächst eine Übersichtsseite eingeblendet, in der alle gemachten Angaben überprüft werden können. Erst dann kann endgültig abgesendet werden.~~

~~Sektion Feuerwerk
Ich verfüge über einen Erlaubnis- oder Befähigungsschein (nicht notwendig, um Mitglied zu werden).
→ „nicht“ statt „Nicht“, Punkt am Ende~~

~~Sektion FEUERWERK.net
Ich bin Mitglied im Forum von FEUERWERK.net möchte, dass der BVPK-Mitgliederbereich für mich freigeschaltet wird. Mit der Angabe meines Mitgliedsname stimme ich der Übermittlung des Mitgliedsnamens an FEUERWERK.net zu.
→ siehe Markierungen~~

~~Sektion Versicherung
Sichere Deine privaten Feuerwerke mit der Haftpflichtversicherung des BVPK ab.
→ Sichere statt Sicher, Punkt am Ende~~

~~Sektion Fördermitgliedschaft
Der Jahresbeitrag für die Grundmitgliedschaft im BVPK beträgt nur 24€/Jahr, um möglichst allen Feuerwerksbegeisterten die Mitgliedschaft im BVPK zu ermöglichen. Für seine Arbeit zum Erhalt des Feuerwerk ist der Verein ständig auf weitere Mittel angewiesen. Mit einer Fördermitgliedschaft unterstützt Du den Verein und die gesamte Community beim Engagement für unsere Leidenschaft! Der Förderbeitrag wird zusätzlich zum Grundbeitrag von 24€/Jahr erhoben. Die Fördermitgliedschaft kann jederzeit gekündigt werden.
→ Ergänzung letzter Satz~~

~~Zwischen Checkbox ich möchte Fördermitglied im BVPK werden!" und den beiden Feldern:
Der jährliche Förderbeitrag ist der gesamte Förderbeitrag pro Jahr. Der Zahlungsrhythmus bestimmt, in welchem Rhythmus entsprechende Teilbeträge abgebucht werden (z.B. 100€ Jahresbeitrag / quartalsweise = 4 Abbuchungen à 25€ pro Jahr + 24€ Grundbeitrag pro Jahr = 124€ insgesamt pro Jahr).~~

~~Aktuell kann das Formular abgeschickt werden, auch wenn kein Zahlungsrhythmus für den Förderbeitrag angegeben ist. Die Angabe sollte verpflichtend sein.~~

**2.2. Änderungen am bisherigen Formular https://bvpk.org/mitglied-werden-firma**

~~ Neu: Angaben überprüfen~~
~~Soweit möglich: Nach Ausfüllen des Formulars wird zunächst eine Übersichtsseite eingeblendet, in der alle gemachten Angaben überprüft werden können. Erst dann kann endgültig abgesendet werden.~~

~~Sektion FEUERWERK.net
Ich bin Mitglied im Forum von FEUERWERK.net möchte, dass der BVPK-Mitgliederbereich für mich freigeschaltet wird. Mit der Angabe meines Mitgliedsname stimme ich der Übermittlung des Mitgliedsnamens an FEUERWERK.net zu.
→ siehe Markierungen~~

~~Sektion Mitgliedsbeitrag
Wir beraten Dich dann gerne persönlich.
→ siehe Markierungen~~

~~Sektion SEPA-Mandat
Mein Gefühl ist, dass es Sinn ergeben könnte, das Feld Zahlungsrhythmus hoch in die Sektion Mitgliedsbeitrag zu ziehen. Das entspräche dann dem Aufbau der Sektion Förderbeitrag im Formular https://bvpk.org/mitglied-werden~~

**Comment by linozen** [comment]
Closing this issue knowing that the following will receive its own issue soon by @flxmts:

2.4 Änderungen am bisherigen Formular https://bvpk.org/mitglied-werden-firma

Neue Sektion Upload Erlaubnisschein

→ Wir sollten besprechen wie viel Aufwand das bedeutet sowie wohin und wie die Dateien ggf. übertragen werden.

• Sektionstext: Bitte laden Sie hier eine Kopie Ihrer Erlaubnis nach §7 SprengG hoch. Mögliche Dateiformate: JPG und PDF, max. XX MB.
• Feld zur Auswahl der Datei + Button Upload
• Checkbox: Ich habe keine Erlaubnis nach §7 SprengG
◦ Wenn gecheckt…
black_small_square ...muss keine Datei hochgeladen werden
black_small_square ...geht ein Textfeld auf mit Beschreibung: Bitte geben Sie kurz an, warum keine Erlaubnis vorliegt.
