### ISSUE TITLE
feat: Add new value to .csv

### ISSUE THREAD

**Issue by flxmts** [BVPyro/front#93]
This change concerns the all existing and future .csv-files that contain member data including an IBAN.

- Add a columns / field called "Zusatzfeld_09"
- In this column, three *** plus the last four digits of the column "IBAN_Nr." should appaer
- 

Example:
- IBAN_Nr. = DE976705500010300351234
- Zusatzfeld_09 = ***1234

**Comment by linozen** [comment]
This is rather an `export` issue. Anyhow, it's implemented now.
