### ISSUE TITLE
Create bvpk.org/feuerwerkshop

### ISSUE THREAD

**Issue by flxmts** [BVPyro/front#94]
Es soll wieder eine Aktion geben wie jene, die über bvpk.org/pyroland lief.

**Formular**

- Beitrittsformular anlegen unter bvpk.org/feuerwerkshop
- Formular identisch mit bvpk.org/pyroland
- Zugriff auf Text über Formular via CMS (wie bei bvpk.org/pyroland)

_Jetzt Mitglied werden im BVPK!
Sei’ dabei! Geben wir dem Feuerwerk eine starke Stimme!
 
Bei Beitritt über dieses Formular ist das erste halbe Jahr Mitgliedschaft für Dich beitragsfrei!
 
Unterstützt von...

Danach nur 24€ im Jahr. Du kannst die Mitgliedschaft jederzeit kündigen._

**Counter**

- Nach 25 Beitritten sollte das Formular nicht mehr funktionieren
- Im Optimalfall erscheint eine einfache Seite / Fenster mit dem Text _Es tut uns Leid. Diese Aktion ist bereits beendet. Du kannst dennoch weiterhin <a href="https://bvpk.org/mitglied-werden"Mitglied bei uns werden.</a>_

**Export**

wie die anderen Mitgliedsanträge in .csv-Datei _JJJJ-MM-TT_SPG.csv_, genau wie für bvpk.org/pyroland, mit folgenden Änderungen:
- Feld _Erhebung_ab_: einheitlich für alle Felder _01.07.2023_
- Feld _promo500_: einheitlich für alle Felder: _f_

**Comment by linozen** [comment]
This is now included:
https://bvpk.org/feuerwerkshop

The site can be edited here:
https://cms.bvpk.org/admin/content/feuerwerkshop_page

I created a column called `promo` (either true or false) and `promo_count` (shows the number of sign-ups via promo, only used for reporting in export).

**Comment by flxmts** [comment]
will the site go offline / redirect to another page once the limit of 25 members is reached?
