### ISSUE TITLE
create bvpk.org/sicher-und-bunt

### ISSUE THREAD

**Issue by flxmts** [BVPyro/front#96]
- create bvpk.org/sicher-und-bunt
- link to a cms-accessible page
- might look similar to bvpk.org/mitgliederversammlung
- maybe the space for text etc. could be a little wider...?

**Comment by linozen** [comment]
This is added now:
https://bvpk.org/sicher-und-bunt

It can be customised here:
https://cms.bvpk.org/admin/content/sicher_und_bunt_page

Here is the corresponding
