### ISSUE TITLE
Changes in main Menu

### ISSUE THREAD

**Issue by flxmts** [BVPyro/front#97]
In the course of december the following points shall be added to the main menu. We will take them online one by one, but possibly the nessecary steps can be prepared, so it's quick in the moment of making them visible.

- [x] _Sicherheit_ directs to https://bvpk.org/sicher-und-bunt
- [ ] _Silvesterfeuerwerk_ directs to https://bvpk.org/novelle-sprengstoffgesetz
- [x] _Petition_ directs to https://bvpk.org/petition

**Comment by linozen** [comment]
Adding the links is trivial. What isn't is putting all the links in one line and keeping an overview as a user. I'd suggest adding some kind of hierarchy or removing some other links. What do you prefer?

**Comment by flxmts** [comment]
Yah, in the medium term we'll definitely need some kind of hierarchy. for know, we could leave "Silvesterfeuerwerk" out of the main menu and would consequently only have two more items. i feel like thiw would still work, both for mobile and large screens.

**Comment by linozen** [comment]
I left _Silvesterfeuerwerk_ out
