### ISSUE TITLE
feat: Create https://bvpk.org/sicher-und-bunt

### ISSUE THREAD

**Issue by flxmts** [BVPyro/front#98]
The content for https://bvpk.org/sicher-und-bunt is ready and needs to be implementet at the page.

It consists of nine square pictures, along with small paragraphs of text. All content can be found here: media.bvpk.org/pics/sicher/content_sicherheit.zip

For information and better understanding: the content has also been published via print, the print file can be found here: media.bvpk.org/pics/sicher/bvpk-sicher-und-bunt.pdf

Stylewise I#m figuering a pattern where a left-aligned pic (with the text to its right) alternates with a following right-aligned pic (with the text to its left). I'm open to any kind of alternative proposals.

**Comment by linozen** [comment]
Why don't you start adding the content in the [editor over here](https://cms.bvpk.org/admin/content/sicher_und_bunt_page) and then I can fine-tune the styling.

Similar to how we did it with the [umwelt page](https://bvpk.org/umweltbelastung-feuerwerk).

**Comment by flxmts** [comment]
That's what I was about to do before I rembered that right / left aligning the images isn't possible via cms (?). Or maybe it ist, editing the source code within the cms? It also might be good to have the colums for images and txt a little wider than on the normal cms created pages. is it possible to change that aspect even though it's a cms creates page?

**Comment by flxmts** [comment]
I started to see what I can do via cms + an online html editor. As I'm a noob both in css and html it's taking ages the results are still pretty poor. I believe it to be better to leave that task to you as a pro. What I started to do in cms might give you an idea of the propsed style. You can either go on there or switch to react. thx

**Comment by linozen** [comment]
This is done now

**Comment by flxmts** [comment]
Here's a few things I'd like to ask you to change for fine tuning the page:

- [ ] I finally got the files without the "bvpk"-sign. best would be to replace all of them.
- [ ] The first picture (the "opener") and the headline could be replaced by this picture: https://media.bvpk.org/pics/sicher/opener.jpg
- [ ] The order of the items / pictures / paragraphs got reverted. Pls use order as in document sichere_anwendung_text.odt
- [ ] The picture of the first paragraph (_Beim Feuerwerken: Löschmittel bereit halten_) got a frame (the other's don't). Best would be to not to have a frame in any of the pics
- [ ] Maybe the pics could be a little larger? If the resolution is too low, let me know...

THX!

**Comment by linozen** [comment]
The file is `./pages/sicher-und-bunt.js`

**Comment by flxmts** [comment]
This is the link to the new image files: media.bvpk.org/pics/sicher/72dpi-rgb_ohnelogo.zip

**Comment by linozen** [comment]
> I finally got the files without the "bvpk"-sign. best would be to replace all of them. https://my.hidrive.com/share/2ntrr.c5.n

Way too small.

> The first picture (the "opener") and the headline could be replaced by this picture: https://media.bvpk.org/pics/sicher/opener.jpg

Two times the headline... once in text and once as text in the image... I don't think this will look good.

>  The order of the items / pictures / paragraphs got reverted. Pls use order as in document sichere_anwendung_text.odt

no problem. almost done

**Comment by flxmts** [comment]
- pics as 300dpi: https://media.bvpk.org/pics/sicher/300dpi-cmyk-druckdateien-ohnelogo.zip - i did have to rename the files because of special characters wich wouldn't allow to upload. they hav the exact same names as before, including "72dpi" although they are in 300dpi
- new pic "opener.jpg" replaces the headline, as it is included in the pic
- i've wo wait for the 3009dpi version frpm our designer, so it's not yet included in the above linked archive.

**Comment by flxmts** [comment]
Here's the Header Pic / "opener" in 300dpi: https://my.hidrive.com/share/l7rkwd58yv

**Comment by linozen** [comment]
I now wrapped the image in an `H1` tag. It's not best practice but satisfies your requirements.
