### ISSUE TITLE
create https://bvpk.org/novelle-sprengstoffgesetz

### ISSUE THREAD

**Issue by flxmts** [BVPyro/front#99]
The page should coontain the same content as https://bvpk.org/aktuelles/positionspapier-silvester It might be possible to take ofer the source code from the CMS.

For reasons of SEO we chose a different string. The page could also be connected to the CMS easy implementation of changes.

**Comment by linozen** [comment]
`https://bvpk.org/novelle-sprengstoffgesetz` now redirects to `https://bvpk.org/aktuelles/positionspapier-silvester`
